name: ACE Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  
  # Deploy Jobs
  deploy:
    runs-on: self-hosted
    #needs: [user_service_sonar_analysis, alert_service_sonar_analysis, vehicle_service_sonar_analysis, nextjs_sonar_analysis, anomaly_detection_sonar_analysis]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy with Docker Compose
        run: |
          docker-compose down
          docker-compose up -d --build

